// AUTO-GENERATED by BetterPortal codegen - DO NOT EDIT
import * as betterTunnelsManagementRoute from "../bp-routes/tunnels/index.js";
import * as betterTunnelsManagementBootstrap1Page from "../bp-routes/tunnels/_theme.bootstrap1/index.js";
import type { BetterPortalRegistry } from "@betterportal/framework";

export const registry: BetterPortalRegistry = {
  routes: [
    {
      viewId: "better-tunnels.management",
      path: "/tunnels",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsManagementRoute.ResponseSchema
      },
      handlers: { GET: betterTunnelsManagementRoute.handleGet },
      title: betterTunnelsManagementRoute.title,
      description: betterTunnelsManagementRoute.description,
      auth: betterTunnelsManagementRoute.auth,
      cacheHints: betterTunnelsManagementRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsManagementBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    }
  ]
};
