// AUTO-GENERATED by BetterPortal codegen - DO NOT EDIT
import * as betterTunnelsCliAuthVerifyRoute from "../bp-routes/cli-auth/verify/index.js";
import * as betterTunnelsCliAuthVerifyBootstrap1Page from "../bp-routes/cli-auth/verify/_theme.bootstrap1/index.js";
import * as betterTunnelsDashboardRoute from "../bp-routes/dashboard/index.js";
import * as betterTunnelsDashboardBootstrap1Page from "../bp-routes/dashboard/_theme.bootstrap1/index.js";
import * as betterTunnelsDownloadsRoute from "../bp-routes/downloads/index.js";
import * as betterTunnelsDownloadsBootstrap1Page from "../bp-routes/downloads/_theme.bootstrap1/index.js";
import * as betterTunnelsLandingRoute from "../bp-routes/landing/index.js";
import * as betterTunnelsLandingBootstrap1Page from "../bp-routes/landing/_theme.bootstrap1/index.js";
import * as betterTunnelsTunnelsRoute from "../bp-routes/tunnels/index.js";
import * as betterTunnelsTunnelsBootstrap1Page from "../bp-routes/tunnels/_theme.bootstrap1/index.js";
import type { BetterPortalRegistry } from "@betterportal/framework";

export const registry: BetterPortalRegistry = {
  routes: [
    {
      viewId: "better-tunnels.cli-auth.verify",
      path: "/cli-auth/verify",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsCliAuthVerifyRoute.ResponseSchema,
        query: betterTunnelsCliAuthVerifyRoute.QuerySchema
      },
      handlers: { GET: betterTunnelsCliAuthVerifyRoute.handleGet },
      title: betterTunnelsCliAuthVerifyRoute.title,
      description: betterTunnelsCliAuthVerifyRoute.description,
      auth: betterTunnelsCliAuthVerifyRoute.auth,
      cacheHints: betterTunnelsCliAuthVerifyRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsCliAuthVerifyBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.dashboard",
      path: "/dashboard",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsDashboardRoute.ResponseSchema
      },
      handlers: { GET: betterTunnelsDashboardRoute.handleGet },
      title: betterTunnelsDashboardRoute.title,
      description: betterTunnelsDashboardRoute.description,
      auth: betterTunnelsDashboardRoute.auth,
      cacheHints: betterTunnelsDashboardRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsDashboardBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.downloads",
      path: "/downloads",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsDownloadsRoute.ResponseSchema
      },
      handlers: { GET: betterTunnelsDownloadsRoute.handleGet },
      title: betterTunnelsDownloadsRoute.title,
      description: betterTunnelsDownloadsRoute.description,
      auth: betterTunnelsDownloadsRoute.auth,
      cacheHints: betterTunnelsDownloadsRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsDownloadsBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.landing",
      path: "/landing",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsLandingRoute.ResponseSchema
      },
      handlers: { GET: betterTunnelsLandingRoute.handleGet },
      title: betterTunnelsLandingRoute.title,
      description: betterTunnelsLandingRoute.description,
      auth: betterTunnelsLandingRoute.auth,
      cacheHints: betterTunnelsLandingRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsLandingBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.tunnels",
      path: "/tunnels",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsTunnelsRoute.ResponseSchema
      },
      handlers: { GET: betterTunnelsTunnelsRoute.handleGet },
      title: betterTunnelsTunnelsRoute.title,
      description: betterTunnelsTunnelsRoute.description,
      auth: betterTunnelsTunnelsRoute.auth,
      cacheHints: betterTunnelsTunnelsRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", render: betterTunnelsTunnelsBootstrap1Page.render }],
          components: [],
          fragments: []
        }
      }
    }
  ]
};
