// AUTO-GENERATED by BetterPortal codegen - DO NOT EDIT
import {
  createHandler as baseCreateHandler,
  createRawHandler as baseCreateRawHandler,
  createStreamHandler as baseCreateStreamHandler
} from "@betterportal/framework";
import type { Plugin } from "../index.js";
type ServiceConfig = Record<string, unknown>;

export const createHandler = baseCreateHandler.forContext<Plugin, ServiceConfig>();
export const createRawHandler = baseCreateRawHandler.forContext<Plugin, ServiceConfig>();
export const createStreamHandler = baseCreateStreamHandler.forContext<Plugin, ServiceConfig>();
