import { createHandler } from "@betterportal/framework";
import { loadBrandAssets } from "../../brand-assets.js";
import { ResponseSchema } from "./index.js";

export { ResponseSchema } from "./index.js";

export default createHandler(
  { response: ResponseSchema },
  async () => {
    const brand = await loadBrandAssets();

    return {
      product: "BetterTunnels",
      domain: "tunnels.betterportal.dev",
      connectHost: "connect.tunnels.betterportal.dev",
      webHost: "betterportal.tunnels.betterportal.dev",
      ...brand,
      cliInstall: [
        "better-tunnels tunnel --port 3100",
        "better-tunnels tunnel --config .bettertunnel"
      ],
      highlights: [
        {
          title: "HTTP and HTTPS tunnels",
          body: "Expose local development servers through generated, short-lived public URLs."
        },
        {
          title: "Verification-first access",
          body: "Visitors pass through a clear development-tunnel warning before reaching a tunnel."
        },
        {
          title: "Built for operations",
          body: "Structured request timings, trace-friendly sessions, and BetterPortal management routes."
        }
      ],
      limits: [
        "Anonymous sessions are temporary.",
        "Tunnel subdomains are generated by the platform.",
        "Registered accounts can unlock higher limits and verification controls later."
      ]
    };
  }
);
