import * as av from "anyvali";
import type { Infer } from "anyvali";
import { createHandler } from "@betterportal/framework";
import { loadBrandAssets } from "../../brand-assets.js";

export const ResponseSchema = av.object({
  product: av.string(),
  domain: av.string(),
  connectHost: av.string(),
  webHost: av.string(),
  logoUrl: av.string(),
  markUrl: av.string(),
  faviconUrl: av.string(),
  cliInstall: av.array(av.string()),
  highlights: av.array(av.object({
    title: av.string(),
    body: av.string()
  })),
  limits: av.array(av.string())
});
export type ResponseData = Infer<typeof ResponseSchema>;

export default createHandler(
  { response: ResponseSchema },
  async () => {
    const brand = await loadBrandAssets();

    return {
      product: "BetterTunnels",
      domain: "tunnels.betterportal.dev",
      connectHost: "connect.tunnels.betterportal.dev",
      webHost: "betterportal.tunnels.betterportal.dev",
      ...brand,
      cliInstall: [
        "better-tunnels tunnel --port 3100",
        "better-tunnels tunnel --config .bettertunnel"
      ],
      highlights: [
        {
          title: "HTTP and HTTPS tunnels",
          body: "Expose local development servers through generated, short-lived public URLs."
        },
        {
          title: "Verification-first access",
          body: "Visitors pass through a clear development-tunnel warning before reaching a tunnel."
        },
        {
          title: "Built for operations",
          body: "Structured request timings, trace-friendly sessions, and BetterPortal management routes."
        }
      ],
      limits: [
        "Anonymous sessions are temporary.",
        "Tunnel subdomains are generated by the platform.",
        "Registered accounts can unlock higher limits and verification controls later."
      ]
    };
  }
);
