// AUTO-GENERATED by BetterPortal codegen - DO NOT EDIT
import * as betterTunnelsCliAuthVerifyRoute from "../bp-routes/cli-auth/verify/index.js";
import * as betterTunnelsCliAuthVerifyGETRoute from "../bp-routes/cli-auth/verify/GET.js";
import * as betterTunnelsCliAuthVerifyBootstrap1PageGET from "../bp-routes/cli-auth/verify/_theme.bootstrap1/GET.js";
import * as betterTunnelsDashboardRoute from "../bp-routes/dashboard/index.js";
import * as betterTunnelsDashboardGETRoute from "../bp-routes/dashboard/GET.js";
import * as betterTunnelsDashboardBootstrap1PageGET from "../bp-routes/dashboard/_theme.bootstrap1/GET.js";
import * as betterTunnelsDownloadsRoute from "../bp-routes/downloads/index.js";
import * as betterTunnelsDownloadsGETRoute from "../bp-routes/downloads/GET.js";
import * as betterTunnelsDownloadsBootstrap1PageGET from "../bp-routes/downloads/_theme.bootstrap1/GET.js";
import * as betterTunnelsLandingRoute from "../bp-routes/landing/index.js";
import * as betterTunnelsLandingGETRoute from "../bp-routes/landing/GET.js";
import * as betterTunnelsLandingBootstrap1PageGET from "../bp-routes/landing/_theme.bootstrap1/GET.js";
import * as betterTunnelsTunnelsRoute from "../bp-routes/tunnels/index.js";
import * as betterTunnelsTunnelsGETRoute from "../bp-routes/tunnels/GET.js";
import * as betterTunnelsTunnelsBootstrap1PageGET from "../bp-routes/tunnels/_theme.bootstrap1/GET.js";
import type { BetterPortalRegistry } from "@betterportal/framework";

export const registry: BetterPortalRegistry = {
  routes: [
    {
      viewId: "better-tunnels.cli-auth.verify",
      path: "/cli-auth/verify",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsCliAuthVerifyGETRoute.ResponseSchema,
        query: betterTunnelsCliAuthVerifyGETRoute.QuerySchema
      },
      methodRoutes: { GET: { method: "GET", schemas: {
        response: betterTunnelsCliAuthVerifyGETRoute.ResponseSchema,
        query: betterTunnelsCliAuthVerifyGETRoute.QuerySchema
      }, handler: betterTunnelsCliAuthVerifyGETRoute.default } },
      handlers: { GET: betterTunnelsCliAuthVerifyGETRoute.default },
      title: betterTunnelsCliAuthVerifyRoute.title,
      description: betterTunnelsCliAuthVerifyRoute.description,
      auth: betterTunnelsCliAuthVerifyRoute.auth,
      cacheHints: betterTunnelsCliAuthVerifyRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", method: "GET", render: betterTunnelsCliAuthVerifyBootstrap1PageGET.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.dashboard",
      path: "/dashboard",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsDashboardGETRoute.ResponseSchema
      },
      methodRoutes: { GET: { method: "GET", schemas: {
        response: betterTunnelsDashboardGETRoute.ResponseSchema
      }, handler: betterTunnelsDashboardGETRoute.default } },
      handlers: { GET: betterTunnelsDashboardGETRoute.default },
      title: betterTunnelsDashboardRoute.title,
      description: betterTunnelsDashboardRoute.description,
      auth: betterTunnelsDashboardRoute.auth,
      cacheHints: betterTunnelsDashboardRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", method: "GET", render: betterTunnelsDashboardBootstrap1PageGET.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.downloads",
      path: "/downloads",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsDownloadsGETRoute.ResponseSchema
      },
      methodRoutes: { GET: { method: "GET", schemas: {
        response: betterTunnelsDownloadsGETRoute.ResponseSchema
      }, handler: betterTunnelsDownloadsGETRoute.default } },
      handlers: { GET: betterTunnelsDownloadsGETRoute.default },
      title: betterTunnelsDownloadsRoute.title,
      description: betterTunnelsDownloadsRoute.description,
      auth: betterTunnelsDownloadsRoute.auth,
      cacheHints: betterTunnelsDownloadsRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", method: "GET", render: betterTunnelsDownloadsBootstrap1PageGET.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.landing",
      path: "/landing",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsLandingGETRoute.ResponseSchema
      },
      methodRoutes: { GET: { method: "GET", schemas: {
        response: betterTunnelsLandingGETRoute.ResponseSchema
      }, handler: betterTunnelsLandingGETRoute.default } },
      handlers: { GET: betterTunnelsLandingGETRoute.default },
      title: betterTunnelsLandingRoute.title,
      description: betterTunnelsLandingRoute.description,
      auth: betterTunnelsLandingRoute.auth,
      cacheHints: betterTunnelsLandingRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", method: "GET", render: betterTunnelsLandingBootstrap1PageGET.render }],
          components: [],
          fragments: []
        }
      }
    },
    {
      viewId: "better-tunnels.tunnels",
      path: "/tunnels",
      methods: ["GET"],
      paramNames: [],
      schemas: {
        response: betterTunnelsTunnelsGETRoute.ResponseSchema
      },
      methodRoutes: { GET: { method: "GET", schemas: {
        response: betterTunnelsTunnelsGETRoute.ResponseSchema
      }, handler: betterTunnelsTunnelsGETRoute.default } },
      handlers: { GET: betterTunnelsTunnelsGETRoute.default },
      title: betterTunnelsTunnelsRoute.title,
      description: betterTunnelsTunnelsRoute.description,
      auth: betterTunnelsTunnelsRoute.auth,
      cacheHints: betterTunnelsTunnelsRoute.cacheHints,
      demoScenarios: [],
      themeRenderers: {
        "bootstrap1": {
          pages: [{ rendererId: "default", type: "page", method: "GET", render: betterTunnelsTunnelsBootstrap1PageGET.render }],
          components: [],
          fragments: []
        }
      }
    }
  ]
};
